### ISSUE TITLE
Nombre para el Meetup ENERO 2017

### ISSUE THREAD

**Issue by cristofer-dev** [Noders/Comunicaciones#19]

**Comment by enBonnet** [comment]
El Warning del panico

**Comment by cristofer-dev** [comment]
**The legend of noders** (by @enBonnet )

**Comment by DMasterIO** [comment]
estuve tratando de hacer algún juego de palabras con la pelicula "Extraordinario" pero no se me ocurrio ninguno y en ingles "Wonder" tampoco ayuda mucho hasta que  pensé... por que no simplemente "**Noders**" ya que se hará un resumen de la trayectoria/historia y por todo lo que se ha pasado para llegar a donde estamos ahora.

En resumen mi propuesta es **Noders**

**Comment by fforres** [comment]
The Lone Ranger - The NodeR-anger ?

**Comment by fforres** [comment]
Igual nadie cacha la wea por `The Lone Ranger` me tinca xD

**Comment by fforres** [comment]
`Los ConeHeads` `Los NodeHeads` ?
`20.000 leguas de viaje submarino` `20000 Horas de .... algo?` ...3 anios tienen 26280 horas? ... no se xD

**Comment by cristofer-dev** [comment]
jajajajaj @fforres !
yo voto por **The legend of noders**

**Comment by DMasterIO** [comment]
me gusta la idea de 26280 hrs de.... podríamos investigar que cosas pasan en 3 años, onda "cada 3 años pasa un cometa X", "en 3 años un arbol hecha raices de 10cm" que se yo, buscar **datos freaks** que pasan en 3 años por último para tirarlo a la presentación, sería entretenido :B

También me gusta **The legend of Noders**
