### ISSUE TITLE
Recordatorio para charlas, sponsors, rrss...

### ISSUE THREAD

**Issue by enBonnet** [Noders/Comunicaciones#2]
¡Hola Javascript@s!

Tu SantiagoJS (link a meetup) de los jueves, normalmente el primer Jueves de cada mes, con comida y cervezas gracias a nuestros auspiciadores (link a lista de auspiciadores).

Sabemos que tienes una charla fantástica que compartir y ¡queremos escucharte! Te invitamos a registrar tu charla (15 – 30 minutos) o lightning (5 – 10 minutos) con una issue en este link (link generar issue), o directamente en GitHub (link github).

Te invitamos a pertenecer a nuestro grupo de patrocinadores. Puedes colaborar con nosotros como venue (prestando espacios para los eventos), con las pizzas o las cervezas. ¡Todo es bienvenido! Déjanos la información para contactarte haciendo click aquí (link generar issue) o escribiéndonos a correo@correo.com (link correo).

Recuerda que puedes charlar con todos los miembros de nuestra comunidad uniéndote al Slack. Solicita tu invitacción haciendo click aquí (link del slack) o siguiéndonos en las redes sociales:

https://twitter.com/noderscl
https://www.facebook.com/NodersCL/

¡Un abrazo asíncrono y nos vemos en el Meetup!

@Noders/core

**Comment by Xabadu** [comment]
Comentarios:

- `!Hola Javascriptos!` -> `¡Hola Javascript@s!`
- `Meetup JS` -> `SantiagoJS`
- `lighthing` -> `lightning`
- `Dejanos` -> `Déjanos`
- `escribiendonos` -> `escribiéndonos`
- `uniéndote al slack, solicita tu invitación haciendo` -> `uniéndote al Slack. Solicita tu invitac...`
- `siéndonos` -> `siguiéndonos`?

**Comment by enBonnet** [comment]
¡Cambios realizados!
