### ISSUE TITLE
Contenido en página meetup

### ISSUE THREAD

**Issue by enBonnet** [Noders/Comunicaciones#3]
¡Hola JavaScript@s!

Tu SantiagoJS (link a meetup) de los jueves, normalmente el primer Jueves de cada mes, con comida y cervezas gracias a nuestros auspiciadores (link a lista de auspiciadores).

Te invitamos a registrar tu charla (15 – 30 minutos) o lightning (5 – 10 minutos) abriendo un issue en este link (link generar issue), o directamente en GitHub (link github).

Para el próximo Meetup tenemos las siguientes charlas y expositores:

Keynotes
•  

Lightning
• 

Estamos buscando sede para los próximos meetups , si quieres que realicemos un meetup en tu empresa cuéntanos aquí [link] y lo coordinamos.

¡Un abrazo asíncrono y nos vemos en el Meetup!

**Comment by Xabadu** [comment]
Comentarios:

- `¡Hola JavaScript@s!`
- `Tu Meetup JS` -> creo que algo con `SantiagoJS` podría ir mejor.
- `lighthing -> lightning`
- `con una issue` -> `abriendo un issue`

**Comment by enBonnet** [comment]
¡Cambios realizados!

**Comment by cristofer-dev** [comment]
Si incluimos la invitación para venue igual ? En plan:

> Estamos buscando sede para los próximos meetups , si quieres que realicemos un meetup en tu empresa cuéntanos aquí [link] y lo coordinamos

🤔

**Comment by rodrigoAdones** [comment]
El primer párrafo podría cambiarse por algo como:

> Los invitamos [‘este jueves’, ‘el primer jueves del mes’, ‘mañana’, …] a Santiago JS, el meetup de JavaScript. Los esperamos con interesantes charlas, un gran ambiente, y algo para comer y beber [‘gracias a nuestros auspiciadores (link lista sponsors)’, ‘gracias a SPONSOR(link), quienes nos recibirán en DIRECCION, LINK MAPA’, ….]

**Comment by enBonnet** [comment]
@cristofer-dev De acuerdo, cambió realizado! :+1:

@L0rdKras Me parece buena la idea, pero más para el correo, que para la página del meetup.

**Comment by cristofer-dev** [comment]
Cerramos esta cosa?
