### ISSUE TITLE
Cambio de ISSUE a PR

### ISSUE THREAD

**Issue by cristofer-dev** [Noders/Comunicaciones#4]
Para trabajar con PR... hacemos un .md para cada publicación que se haga y agrupamos pro mes ? @Xabadu @fforres @DMaster69 @enBonnet @luchosrock @L0rdKras

**Comment by fforres** [comment]
I ❤️  PR's

Me tinca caleta, tienes mi plus one

**Comment by Xabadu** [comment]
Yes por favor.
